name: "Check CodeScene Coverage"
description: "Run CodeScene coverage gate check"

inputs:
  access-token:
    description: "CodeScene API access token"
    required: true
  project-url:
    description: "CodeScene project URL"
    required: true
  coverage-files:
    description: "Glob pattern for coverage files"
    required: true
    default: "coverage.out"

runs:
  using: "composite"
  steps:
    - name: Download cs-coverage tool
      shell: bash
      run: |
        curl -sSL https://downloads.codescene.io/enterprise/cli/cs-coverage/linux-amd64/cs-coverage -o cs-coverage
        chmod +x cs-coverage

    - name: Run coverage check
      shell: bash
      env:
        CODESCENE_ACCESS_TOKEN: ${{ inputs.access-token }}
      run: |
        ./cs-coverage \
          --project-url "${{ inputs.project-url }}" \
          --coverage-files "${{ inputs.coverage-files }}" \
          --format go-cover
